// All player-facing text lives here, never hardcoded in components.
export const texts = {
  homeTitle: "Among Hugo's House",
  testButton: 'TEST PORTE',
  testMinigame1Button: 'TEST MINIGAME1',
  miniGameInstruction: "CODE D'ACCÈS",
  miniGameSuccess: 'OUVERTURE PORTE',
  miniGameFail: 'CODE ERRONÉ',
  taskSuccess: 'TÂCHE COMPLÈTE',
  colorGameInstruction: 'RANGE LES BOÎTES',
  scanButton: 'Scanner un QR code',
  closeButtonLabel: 'Fermer',
  scanAgainButton: 'Scanner à nouveau',
  scanResultLabel: 'QR lu :',
  cameraError: "Impossible d'accéder à la caméra.",
  title: 'Among Us IRL',
  namePrompt: 'Ton prénom',
  namePlaceholder: 'Ex : Marie',
  joinButton: 'REJOINDRE LA PARTIE',
  joinError: 'CONNEXION IMPOSSIBLE',
  takeSelfieButton: 'PRENDRE UN SELFIE',
  captureSelfieButton: 'CAPTURER',
  retakeSelfieButton: 'REPRENDRE',
  selfieError: 'CAMÉRA INDISPONIBLE',
  connecting: 'Connexion au serveur…',
  playersHeading: 'Joueurs connectés',
  noPlayers: 'Aucun joueur pour le moment.',
  disconnected: 'Connexion perdue, nouvelle tentative…',
};
