// All player-facing text lives here, never hardcoded in components.
export const texts = {
  homeTitle: "Among Hugo's House",
  testButton: 'Bouton test',
  miniGameInstruction: "CODE D'ACCÈS",
  miniGameSuccess: 'OUVERTURE PORTE',
  miniGameFail: 'CODE ERRONÉ',
  scanButton: 'Scanner un QR code',
  closeButtonLabel: 'Fermer',
  scanAgainButton: 'Scanner à nouveau',
  scanResultLabel: 'QR lu :',
  cameraError: "Impossible d'accéder à la caméra.",
  title: 'Among Us IRL',
  namePrompt: 'Ton prénom',
  namePlaceholder: 'Ex : Marie',
  joinButton: 'Rejoindre',
  connecting: 'Connexion au serveur…',
  playersHeading: 'Joueurs connectés',
  noPlayers: 'Aucun joueur pour le moment.',
  disconnected: 'Connexion perdue, nouvelle tentative…',
};
