// All player-facing text lives here, never hardcoded in components.
export const texts = {
  homeTitle: 'AMONG HOUSE',
  testButton: 'TEST PORTE',
  testMinigame1Button: 'TEST MINIGAME1',
  miniGameInstruction: "CODE D'ACCÈS",
  miniGameSuccess: 'OUVERTURE PORTE',
  miniGameFail: 'CODE ERRONÉ',
  taskSuccess: 'TÂCHE COMPLÈTE',
  colorGameInstruction: 'RANGE LES BOÎTES',
  scanButton: 'Scanner un QR code',
  closeButtonLabel: 'Fermer',
  scanAgainButton: 'Scanner à nouveau',
  scanResultLabel: 'QR lu :',
  cameraError: "Impossible d'accéder à la caméra.",
  title: 'Among Us IRL',
  namePrompt: 'Nom',
  namePlaceholder: 'Ex : Marie',
  joinButton: 'REJOINDRE',
  joinError: 'CONNEXION IMPOSSIBLE',
  takeSelfieButton: 'PRENDRE UN SELFIE',
  captureSelfieButton: 'CAPTURER',
  retakeSelfieButton: 'REPRENDRE',
  selfieError: 'CAMÉRA INDISPONIBLE',
  previousHat: 'Chapeau précédent',
  nextHat: 'Chapeau suivant',
  connecting: 'Connexion au serveur…',
  noPlayers: 'Aucun joueur pour le moment.',
  disconnected: 'Connexion perdue, nouvelle tentative…',
  playButton: 'JOUER',
  emptySlot: 'En attente…',
  disconnectButton: 'SE DÉCONNECTER',
  backButtonLabel: 'Retour à la connexion',
  testChatButton: 'TEST CHAT',
  chatTitle: 'Chat',
  chatPlaceholder: 'Message…',
  chatSendButton: 'ENVOYER',
  chatEmpty: 'Aucun message pour le moment.',
  roleInnocent: 'INNOCENT',
  roleTraitor: 'TRAÎTRE',
};
